server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CoderYe13/cloud-config-server.git
          #搜索目录
          search-paths: cloud-config-server
          #读取分支
      label: master

eureka:
  client:
    #表示是否将自己注册进eurekaserver默认为true
    register-with-eureka: true
    #是否eurekaserver抓取已有的注册信息。默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon才能进行负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  #主机实例名
  instance:
    instance-id: config-server3344
    prefer-ip-address: true
##暴露bus地址
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
