server:
  port: 80


#微服务别名---注册中心使用zookeeper
spring:
  application:
    name: cloud-order-service
  cloud:
    zookeeper:
      connect-string: 192.168.0.108:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456