server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.110:1111 #localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
