server:
  port: 8801
spring:
  application:
    name: stream-kafka-provider8801
eureka:
  client:
    #表示是否将自己注册进eurekaserver默认为true
    register-with-eureka: true
    #是否eurekaserver抓取已有的注册信息。默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon才能进行负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


#主机实例名
  instance:
    instance-id: send-8801.com
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2  #设置心跳的时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5 #如果想在超过了5秒的间隔（默认90秒）
