server:
  port: 9333

eureka:
  client:
    #表示是否将自己注册进eurekaserver默认为true
    register-with-eureka: true
    #是否eurekaserver抓取已有的注册信息。默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon才能进行负载均衡
    fetch-registry: true
    service-url:
           defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-zuul-9333
    prefer-ip-address: true

spring:
  application:
    name: gateway-zuul
zuul:
 # prefix: /api  #网关前缀
  ignored-services: "*"  #忽略掉所有的微服务名，防止微服务名暴露
  routes:
    provider8001:  #微服务配置
      serviceId: cloud-payment-service
      path: /provider/**
  strip-prefix: true  #代理后的路径不移除前缀/api
